using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; //PK
using System.ComponentModel.DataAnnotations.Schema; // Autogenerated
using System.Linq;
using System.Web;


namespace ClientBook.Models
{
    public class Client
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int clientid { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public DateTime dateofbirth { get; set; }
    }

 

}